# 서버 포트 설정 (선택 사항)
server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      force: true

# 데이터베이스 연결을 의미 - 내장된 커넥션 풀 라이브러리 (예: HikariCP)를 사용하여, 고성능의 데이터베이스 연결 관리가 가능
spring:
  datasource: 
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 3000 # 3초 
        
    url: jdbc:mysql://localhost:3306/todo?serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd1234


mybatis:
  mapper-locations:
  - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true    
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# MyBatis 로그 설정 (선택 사항)
logging:
  level:
    org.mybatis.spring: debug
